name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6
        pip install PyQt6-Qt6
        pip install PyQt6-sip
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --windowed --name VideoPlayer video_player.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoPlayer-Windows
        path: dist/VideoPlayer
